# Generated by Django 3.0.8 on 2020-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20200810_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
